    ---
deployment:
  tasks:
    - export DEPLOYPATH=/home/economia13d08a61/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git # Remove a pasta .git copiada, se houver
    - /bin/rm -rf $DEPLOYPATH/.cpanel.yml # Remove o próprio .cpanel.yml copiado, se não quiser ele na produção