---
deployment:
  tasks:
    - export DEPLOYPATH=/home/economia13d08a61/public_html/
    - export REPO_BASE_PATH=economia_futurista/ # <-- NOVA LINHA CRÍTICA!
    
    # Copia os arquivos HTML e JSON da subpasta 'economia_futurista'
    - /bin/cp $REPO_BASE_PATHarticles.json $DEPLOYPATH
    - /bin/cp $REPO_BASE_PATHartigo.html $DEPLOYPATH
    - /bin/cp $REPO_BASE_PATHartigos.html $DEPLOYPATH
    - /bin/cp $REPO_BASE_PATHcontato.html $DEPLOYPATH
    - /bin/cp $REPO_BASE_PATHindex.html $DEPLOYPATH
    - /bin/cp $REPO_BASE_PATHsobre.html $DEPLOYPATH
    
    # Copia as pastas css e js recursivamente da subpasta 'economia_futurista'
    - /bin/cp -R $REPO_BASE_PATHcss $DEPLOYPATH
    - /bin/cp -R $REPO_BASE_PATHjs $DEPLOYPATH
    
    # Limpeza (opcional, mas boa prática)
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -rf $DEPLOYPATH/.cpanel.yml